// Code generated by "varhandler -func UserGet"; DO NOT EDIT

package main

import "net/http"

func UserGetHandler(w http.ResponseWriter, r *http.Request) {
	var err error

	param0, err := HTTPUserName(r)
	if err != nil {
		HandleHttpErrorWithDefaultStatus(w, r, http.StatusBadRequest, err)
		return
	}

	var resp interface{}

	var status int

	resp, status, err = UserGet(param0)
	if err != nil {
		HandleHttpErrorWithDefaultStatus(w, r, http.StatusInternalServerError, err)
		return
	}

	if status != 0 {
		w.WriteHeader(status)
	}

	if resp != nil {
		HandleHttpResponse(w, r, resp)
	}

}
